### PR TITLE
Support python 3.12

### PR DESCRIPTION
**Pull request by andersonhc**
Add python 3.12 on the CI

**Checklist**:

- [ ] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [ ] A unit test is covering the code added / modified by this PR

- [ ] This PR is ready to be merged 

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [ ] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/py-pdf/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Comment by andersonhc** [comment]
JPype is failing on python 3.12 and they already have an issue reporting this:
https://github.com/jpype-project/jpype/issues/1147

**Review by Lucas-C — APPROVED** [review]

**Comment by Lucas-C** [comment]
Hi @andersonhc

Was it intentional to merge this PR, while the GitHub Actions pipeline was still failing?

I'm not sure if this is related, but the last pipeline execution on `master` following this merge is failing: https://github.com/py-pdf/fpdf2/actions/runs/7096327931

**Comment by Lucas-C** [comment]
I think the problem only occurs under Python 3.7 that installs `fonttools==4.38.0`, which is an older version of `fonttools`: https://pypi.org/project/fonttools/#history

The problem is that when you merged this PR on `fpdf2` master branch, you restored Python 3.7 in our GitHub Actions matrix:
https://github.com/py-pdf/fpdf2/commit/a0bf1cd82e27840a7bf823dc18825f85a99edb66

A rebase should probably have been performed before merging.
I'm going to fix this now.

**Comment by Lucas-C** [comment]
Fixed in https://github.com/py-pdf/fpdf2/commit/c4da2ef98a4fb22d4e34dead33d839077e8b690f

**Comment by andersonhc** [comment]
Thank you for fixing it @Lucas-C,
I messed up resolving conflict after the rebase and didn't notice

**Pull request merged**
