### PR TITLE
Fix spelling mistaking for Khmer tutorial

### PR DESCRIPTION
**Pull request by kuth-chi**
Fix spelling mistaking for Khmer tutorial: "ភាសខ្មែរ" should be replaced by "ភាសាខ្មែរ".

**Checklist**:

- [x] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [ ] A unit test is covering the code added / modified by this PR

- [x] This PR is ready to be merged 

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [x] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/py-pdf/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Comment by Lucas-C** [comment]
Hi @kuth-chi 🙂

Sorry but I don't quite understand the goal of this PR 😅
Why did you submit it?

**Comment by kuth-chi** [comment]
Sorry, I was do some update on my fork repo, and request to update my repo.

**Comment by Lucas-C** [comment]
OK, no worry if this PR was created by mistake 😊
Closing it now

**Comment by Lucas-C** [comment]
> I found a mistake of spelling in Khmer on readme.md is "ភាសខ្មែរ" not correct the correct is "ភាសាខ្មែរ" I want to correct it. How to achieve it. Just can from my fork repository and create pull only readme.md file?

Oh alright!
If your goal was to fix a spelling mistake, then this PR is perfectly fine.
I'm going to reopen it and edit the title & description to clarify its goal.

Also, the same word with the same spelling is used in the files `README.md`, `docs/index.md`, `mkdocs.yml` and `CHANGELOG.md`: should the spelling also be corrected there?

**Review by kuth-chi — COMMENTED** [review]
Please merge this pull request to fix some word of Khmer spelling .

**Comment by Lucas-C** [comment]
Hi @kuth-chi

As I mentioned before, I will not merge this PR until:
* it is rebased on the `master` branch of this repository, to resolve the existing conflict on `README.md`
* the correction is also applied to the other files I mentioned, to ensure the spelling consistency

**Pull request closed without merging**
