### PR TITLE
Dutch Tutorial-nl.md added

### PR DESCRIPTION
**Pull request by Polderrider**
Dutch translation added

e.g. Fixes #0 

**Checklist**:

- [x] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [ ] A unit test is covering the code added / modified by this PR N/A

- [x] This PR is ready to be merged 

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder N/A

- [x] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/py-pdf/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Comment by Lucas-C** [comment]
Thank you for this contribution @Polderrider!

Could you please also insert links to this tutorial in the following files, as part of this PR?
* in `README.md`, in the "Documentation" section
* in `docs/index.md`
* in `tutorial/notebook.ipynb`
* in `CHANGELOG.md`, in the topmost "Added" section, like this:

> - tutorial in Dutch: [Handleiding](https://py-pdf.github.io/fpdf2/Tutorial-nl.html) - thanks to @Polderrider

**Comment by Lucas-C** [comment]
> Done. But each change went through as a individual PR. Need to figure out how to group the changes together in a single PR next time.

Could you try to figure this out this time, please? 😅
Having a single PR for this instead of **five** would be a lot easier to manage for us.

**Comment by gmischler** [comment]
> Done. But each change went through as a individual PR. Need to figure out how to group the changes together in a single PR next time.

Just commit the changes to your forked branch ([Polderrider:adding-dutch-translation](https://github.com/Polderrider/fpdf2/tree/adding-dutch-translation), the source of the PR), and they will be automatically included in the PR.

Do NOT create a new branch for every change.

**Comment by Polderrider** [comment]
Closed #1049.  Added #1054 to combine multiple commits in one PR

**Pull request closed without merging**
