### PR TITLE
Resolves #1311 - `<a>` HTML tag applying styling rules to all following content

### LINKED ISSUE #1311: The default underlines of link (<a>) tags continue past the link into the remainder of the sentence.
When creating a link using an `<a></a>` tag and `pdf.write_html()`, the underline which normally appears on links continues past the link and throughout the remainder of the sentence.

**Error details**
No exceptions are raised

**Minimal code**
```python
from fpdf import FPDF
pdf = FPDF()
pdf.add_page()
pdf.write_html(
    """
    The default <a href="https://www.google.com/" target="_blank">link underline</a> continues past the end of the link.
    """
)
pdf.write_html(
    """
    <a href="https://www.google.com/" target="_blank">It also occurs</a> when the link starts the sentence.
    """
)
pdf.output("link.pdf")
```
**Screenshot of output PDF**
link.pdf

**Environment**
Please provide the following information:
* **Operating System**: Ubuntu 22.04.1 LTS
* **Python version**:Python 3.10.8
* **`fpdf2` version used**: Unreleased version @ git+https://github.com/py-pdf/fpdf2.git@fb1b01d9113e7b8326f9d12491679b5c52f734d3

### PR DESCRIPTION
**Pull request by K-Hern**
Fixed rendering of content following `<a>` tags; now correctly resets emphasis style post `</a>` tag: hyperlink styling contained within the tag authority. Updated documentation to reflect this change.

Also corrected minor typo in documentation.

**Checklist**:

- [ ] A unit test is covering the code added / modified by this PR

- [x] This PR is ready to be merged 

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [x] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/py-pdf/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Comment by Lucas-C** [comment]
Thank your for your contribution @K-Hern 👍 🙂 

Could you please rebase your branch on this repo `master` branch?

I fixed the problem that made the GitHub Actions pipeline fail.

**Comment by Lucas-C** [comment]
Hi @K-Hern

I performed the branch rebase.

The addition of a new simple unit test covering this case will be required before merging this PR.

Are you stilling willing to continue the work on this?
If so, this can really wait a few weeks, no hurry.

Else I'll take the time to finish it.

**Review by Lucas-C — APPROVED** [review]

**Comment by Lucas-C** [comment]
I added a unit test.

Merging once the pipeline is ✅

**Comment by K-Hern** [comment]
Lucas,

Apologies for the late response. Its been a hectic time for me! I see you have added the unit test and completed all other necessary changes - Thank you!

**Pull request merged**
