### PR TITLE
Bangla Tutorial Added

### LINKED ISSUE #267: Translate the one-page tutorial in your language!
The tutorial is a simple Markdown document:
* rendered as HTML: https://pyfpdf.github.io/fpdf2/Tutorial.html
* source: https://github.com/PyFPDF/fpdf2/blob/master/docs/Tutorial.md

It is currently available in several languages, listed [in the README](https://github.com/PyFPDF/fpdf2#documentation) and [the documentation index page](https://pyfpdf.github.io/fpdf2/#tutorials).

PRs are very welcome to add new translations!
PR authors will be added to the [contributors list & map](https://github.com/PyFPDF/fpdf2#contributors-).

---

Guidelines:
* [open a Pull Request](https://opensource.guide/how-to-contribute/#opening-a-pull-request) that creates or modifies the corresponding `docs/Tutorial-xy.md` file, taking inspiration from `docs/Tutorial.md` (where `xy` is the [ISO_639-1 language code](https://en.wikipedia.org/wiki/ISO_639-1))
* if you created a new file, add a reference to it in `docs/index.md`, `mkdocs.yml`, `README.md` and `CHANGELOG.md`, taking inspiration from the references to existing translated tutorials

### PR DESCRIPTION
**Pull request by ssavi-ict**
- Fixes #267 
- Updated Bangla Tutorial 

**Checklist**:

- [ ] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [ ] A unit test is covering the code added / modified by this PR

- [ ] This PR is ready to be merged 

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [ ] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/PyFPDF/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Comment by ssavi-ict** [comment]
@Lucas-C, I pushed the changes again. Could you check again, please?

**Review by Lucas-C — APPROVED** [review]

**Comment by Lucas-C** [comment]
@allcontributors please add @ssavi-ict for translation

**Comment by ssavi-ict** [comment]
@Lucas-C 
This tutorial has not yet been published on the page. Is there anything I can do?

**Comment by Lucas-C** [comment]
It is published, you can find it here: https://pyfpdf.github.io/fpdf2/Tutorial-%E0%A4%B9%E0%A4%BF%E0%A4%82%E0%A4%A6%E0%A5%80.html

But I'm in the process of renaming the URL, so it should soon be there: https://pyfpdf.github.io/fpdf2/Tutorial-bn.html

**Comment by ssavi-ict** [comment]
> It is published, you can find it here: https://pyfpdf.github.io/fpdf2/Tutorial-%E0%A4%B9%E0%A4%BF%E0%A4%82%E0%A4%A6%E0%A5%80.html
> 
> But I'm in the process of renaming the URL, so it should soon be there: https://pyfpdf.github.io/fpdf2/Tutorial-bn.html

Great. I got it. Thank You.

**Pull request merged**
