### PR TITLE
Refactoring multi_cell for fewer PDF objects

### PR DESCRIPTION
**Pull request by mjasperse**
This is a continuation of my previous PR #1026 looking into how `multi_cell()` works. The idea is that instead of treating each line of the multi_cell independently with its own border and fill, we instead draw a single background rect first and then put the text on top. 

For a multi_cell with both `border` and `fill` enabled, this eliminates approx 3 elements per line (the individual L/R border lines and background rect), and also eliminates possible gaps in the background fill between the individual lines - which can be noticeable in some circumstances.

Along these lines I also noticed that when `border='LTRB'` (which is often how full borders is designated), the result contains 4 lines + fill, whereas it should just be a single stroked fill - so I have added logic to handle this.

I'm raising this as a draft PR initially for some feedback, as it breaks a lot of test cases since they now contain fewer objects and I'm going through them one-by-one to ensure the behaviour is as expected.

**Checklist**:

- [X] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [x] A unit test is covering the code added / modified by this PR

- [X] This PR is ready to be merged 

- [x] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [x] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/py-pdf/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Comment by mjasperse** [comment]
I finished going through the tests manually to verify no regressions.

The only test with changed behaviour is `test_multi_cell_table_with_max_line_height()` but I want to verify the expected behaviour in this case - see following screenshot with new behaviour on left, old on right
image

My interpretation of this test is that there should only be one ln break between the tables, so the old behaviour has unexpectedly large gap.

The other thing I noticed during my manual validation is the link area doesn't look correct for the test_links cases. The following screenshot shows the active area of the link which seems abnormally large - I would expect it cover just the multi_cell area containing the link? Is this a bug or is it expected behaviour?

**Review by andersonhc — APPROVED** [review]

**Comment by andersonhc** [comment]
@mjasperse Awesome work on this PR!

**Comment by Lucas-C** [comment]
Yes, excellent job on this @mjasperse, thank you!

I noticed you also allowed for page number to be provided in `<a href>`, that's nice!
Maybe we should add a unit test for that later on.

**Comment by mjasperse** [comment]
> Maybe we should add a unit test for that later on.

Actually, this is already part of `test_internal_links()` for the case "Link defined with FPDF.write_html" - but had the incorrect behaviour previously and tried to open an external file instead :)

**Comment by Lucas-C** [comment]
> > Maybe we should add a unit test for that later on.
> 
> Actually, this is already part of `test_internal_links()` for the case "Link defined with FPDF.write_html" - but had the incorrect behaviour previously and tried to open an external file instead :)

Alright! Great then 😊

**Pull request merged**
