### PR TITLE
Fix: markdown now processed correctly when adding BI or negating B or I base font - fix #1094

### LINKED ISSUE #1094: Markdown formatting in cell and multicell fails for some combinations
**Environment**
Windows  WSL running Ubuntu 22.04.2
Python 3.11.0
FPDF 2.7.7 from conda (and tested with latest main branch)

**Issue**
When using `cell()` or `multicell()` with `markdown=True`, an error is thrown for some combinations of initial font and markdown modifications. Specifically, the following examples work:

```python
from fpdf import FPDF

pdf = FPDF('P', 'mm', 'Letter')
pdf.add_page()

# works
pdf.set_font('Courier', '', 10)
pdf.cell(40, 10, markdown=True, text="normal")
pdf.ln(10)

# works
pdf.set_font('Courier', '', 10)
pdf.cell(40, 10, markdown=True, text="__italic__")
pdf.ln(10)

# works
pdf.set_font('Courier', '', 10)
pdf.cell(40, 10, markdown=True, text="**bold**")
pdf.ln(10)

# works
pdf.set_font('Courier', 'BI', 10)
pdf.cell(40, 10, markdown=True, text="bold italic")
pdf.ln(10)

pdf.output("test.pdf")
```

While these all fail:

```python
from fpdf import FPDF

pdf = FPDF('P', 'mm', 'Letter')
pdf.add_page()

# fails when combining bold and italic from normal base font
pdf.set_font('Courier', '', 10)
pdf.cell(40, 10, markdown=True, text="__**bold italic**__")
pdf.ln(10)

# fails when adding italic to bold base font
pdf.set_font('Courier', 'B', 10)
pdf.cell(40, 10, markdown=True, text="__bold italic__")
pdf.ln(10)

# fails when negating bold or italic base font
pdf.set_font('Courier', 'B', 10)
pdf.cell(40, 10, markdown=True, text="**normal**")

pdf.output("test.pdf")
```

However, No error occurs if I combine the working and failing snippets into a single script.

To illustrate an error message, If I try just one example of the failing snippets above

```python
from fpdf import FPDF

pdf = FPDF('P', 'mm', 'Letter')
pdf.add_page()

pdf.set_font('Courier', '', 10)
pdf.cell(40, 10, markdown=True, text="__**bold italic**__")
pdf.ln(10)

pdf.output("test.pdf")
```

I get 

```
Traceback (most recent call last):
  File "/mnt/d/work/./test.py", line 30, in <module>
    pdf.cell(40, 10, markdown=True, text="__**bold italic**__")
  File "/home/alan/mambaforge/envs/elgato/lib/python3.11/site-packages/fpdf/fpdf.py", line 217, in wrapper
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/mambaforge/envs/elgato/lib/python3.11/site-packages/fpdf/deprecation.py", line 32, in wrapper
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/mambaforge/envs/elgato/lib/python3.11/site-packages/fpdf/fpdf.py", line 2836, in cell
    styled_txt_frags = self._preload_font_styles(text, markdown)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/mambaforge/envs/elgato/lib/python3.11/site-packages/fpdf/fpdf.py", line 3193, in _preload_font_styles
    frag.font = self.fonts[frag.font_family + frag.font_style]
                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'courierBI'
```

This error does not occur if I first set the font to be Courier with Bold and Italic and then change it back to the normal Courier. i.e.,

```python
from fpdf import FPDF

pdf = FPDF('P', 'mm', 'Letter')
pdf.add_page()

pdf.set_font('Courier', 'BI', 10)
pdf.set_font('Courier', '', 10)
pdf.cell(40, 10, markdown=True, text="__**bold italic**__")
pdf.ln(10)

pdf.output("test.pdf")
```

### PR DESCRIPTION
**Pull request by Alan-Collins**
Fixes #1094

 

**Checklist**:

- [ ] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [ ] A unit test is covering the code added / modified by this PR

- [x] This PR is ready to be merged 

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [ ] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/py-pdf/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Comment by Lucas-C** [comment]
Hi @Alan-Collins

Thank you for your contribution!

Could you please also add a unit test covering this case?

We also usually add en entry in `CHANGELOG.md` mentioning bugfixes.
You can add it as part of this PR, or else a maintainer will do it later on.

**Comment by Alan-Collins** [comment]
Happy to! I might be able to get to this next week. If not the next.

**Comment by andersonhc** [comment]
I am merging this PR and I'll open another one to add test and changelog

**Comment by andersonhc** [comment]
@allcontributors please add @Alan-Collins for code

**Pull request merged**
