### PR TITLE
Doc: mention that text() does lack features (#1265)

### LINKED ISSUE #1265: Text shaping does not work with `text()`
When using `text()` with shaping enabled like documented in 
https://py-pdf.github.io/fpdf2/Text.html  and https://py-pdf.github.io/fpdf2/TextShaping.html the created text isn't shaped.

**Minimal code**

```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.add_font('khmer', '', 'NotoSansKhmer-Regular.ttf')
pdf.set_font('khmer', size=32)
pdf.set_text_shaping(True)
pdf.text(20,100, text="ភាសាខ្មែរ")

pdf.set_xy(20,110)
pdf.cell(text="ភាសាខ្មែរ")

pdf.set_xy(20,130)
pdf.write(None, text="ភាសាខ្មែរ")

pdf.output("hello_world.pdf")
```
In the example Noto Sans Khmer was used (can be downloaded from https://fonts.google.com/noto/specimen/Noto+Sans+Khmer) but the problem occurs with other fonts as well.

The following screenshot shows the output of the example. Text placed with `write()` and `cell()` is represented correctly but `text()` (first line)  isn't. 
Screenshot 2024-09-20 at 12 19 23

**Environment**
Please provide the following information:
* **Operating System**: MacOS, Linux (Debian/Ubuntu)
* **Python version**:  Python 3.10.14, Python 3.11.9, Python 3.12.4
* **`fpdf2` version used**: master 90c7d7f8780ff524a469fb7deff4dffb88be3a5f

Thank you for your efforts and work on fpdf2.

### PR DESCRIPTION
**Pull request by bmiklautz**
* adept comparison table in Text.md (add text shaping)
* add a note in the functions doc string

Fixes #1265 

**Checklist**:

- [ ] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [ ] A unit test is covering the code added / modified by this PR N/A

- [x] This PR is ready to be merged

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder  N/A

- [ ] A mention of the change is present in `CHANGELOG.md`  N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/py-pdf/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Comment by Lucas-C** [comment]
I agree that addition about text shaping in the table is very welcome,
but I'm not sure that we should communicate about `FPDF.text()` being deprecated / left only for backward compatibility...

For precise text positioning for exemple, `FPDF.text()` does not add a `.c_margin` horizontally around text and can be useful.

**Comment by Lucas-C** [comment]
Also, the GitHub Actions pipeline on this PR due to an issue I just fixed in https://github.com/py-pdf/fpdf2/pull/1268

Could you rebase this PR so that the Github Actions pipeline passes, please?

**Comment by bmiklautz** [comment]
@Lucas-C thanks for the feedback. It's rebased and I've removed the note about `backwards compatibility`.

**Comment by Lucas-C** [comment]
Thank you for your contribution @bmiklautz 👍

**Pull request merged**
