### PR TITLE
Update README.md

### LINKED ISSUE #959: Update Deprecated Parameter Name in README.md
Describe the bug

**Update Deprecated Parameter Name**
I encountered a DeprecationWarning while using the 'fpdf' library, indicating that the parameter 'txt' has been renamed to 'text' in version 2.7.6.

**Minimal code**
Please include some minimal Python code reproducing your issue:
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.set_font('helvetica', size=12)
pdf.cell(txt="hello world")
# DeprecationWarning: The parameter "txt" has been renamed to "text" in 2.7.6

...
```

**Environment**
Please provide the following information:
* **Operating System**:  Linux (Ubuntu 22.04.2)
* **Python version**: 3.10.12
* **`fpdf2` version used**: 2.7.6

I would like to contribute to the project by submitting a pull request to update the README.md file and reflect the parameter name change from 'txt' to 'text.' Please let me know if this is an acceptable change, and I'm happy to work on the pull request.

### PR DESCRIPTION
**Pull request by rakesh-nj**
Updated parameter 'txt' to 'text' in README.md

 Fixes #959  

**Checklist**:

- [x] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [N/A] A unit test is covering the code added / modified by this PR

- [x] This PR is ready to be merged 

- [N/A] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [N/A] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/py-pdf/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Comment by Lucas-C** [comment]
Quoting @andersonhc in #959:

> Hi Rakesh, Of course it an acceptable change, we'll be glad to receive and review your PR. If you go on the github search bar and search for "txt=" you will find some tutorial and test files that weren't updated either - can you add them on your PR too?

Also, are you contributing as part of https://hacktoberfest.com? 🙂

**Comment by rakesh-nj** [comment]
> Quoting @andersonhc in #959:
> 
> > Hi Rakesh, Of course it an acceptable change, we'll be glad to receive and review your PR. If you go on the github search bar and search for "txt=" you will find some tutorial and test files that weren't updated either - can you add them on your PR too?
> 
> Also, are you contributing as part of https://hacktoberfest.com? 🙂
Yes . I am contributing as part of https://hacktoberfest.com.

**Review by gmischler — CHANGES_REQUESTED** [review]
As @andersonhc has requested over in #959, could you please do a [search](https://github.com/search?q=repo%3Apy-pdf%2Ffpdf2%20txt%3D&type=code) and fix any uses of `txt=` in the test and tutorial files as well?

**Comment by gmischler** [comment]
redundant to #974

**Pull request closed without merging**
