### PR TITLE
updates to SVG conversion: defs, shapes and clipping paths

### LINKED ISSUE #858: svg exported from matplotlib not inserted correctly - add support for clip-path & clipPath
Describe the bug

**Error details**

Matplotlib plots where the plot contents exceed the figure range are included wrongly in the pdf when exported to svg.

Expected:
(this is the .svg file exported from matplotlib)
matplotlib

Result:
image

**Minimal code**
Please include some minimal Python code reproducing your issue:
```python
from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.image("matplotlib.svg")
pdf.output("matplotlib.pdf")
```
matplotlib.pdf

**Environment**

Please provide the following information:
OS: Windows 10
Python 3.11
matplotlib: matplotlib-3.7.2
fpdf2: latest master branch

### PR DESCRIPTION
**Pull request by afriedman412**
Fixes #858
- SVG conversion now handles clipping paths
- various shapes (`rect`, `circle` etc) now work in `defs` 
- `defs` tags get read first instead of sequentially
SVGs allow you pre-define objects anywhere, which means they can be cross-referenced before they are created. Our code didn't do that, but now it does.

ie fpdf can accurately convert this file now:
```
<svg>
<use href="#square" x="0" y="0" />
<defs>
  <rect id="square" width="100" height ="100" />
</defs>
</svg>
```

**Checklist**:

- [x] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [x] A unit test is covering the code added / modified by this PR

- [x] This PR is ready to be merged 

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [ ] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/py-pdf/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Review by gmischler — APPROVED** [review]
Looking good!

You probably want to remove those "actual.pdf", "actual_qpdf.pdf", and "expected_qpdf.pdf" files. I assume they are left over from your testing experiments?

**Comment by gmischler** [comment]
A few points more to round this up:
* I just noticed another left over file "output_audit.py".
* Your changes to ".gitignore" also don't look like they are of general use outside this PR, so please remove them as well.
* Is there a test that loads all the possible shapes through defs and inserts them into the drawing? You might think that if rect and circle work, then they all should. But to avoid regressions with any possible changes in the future, it's best to just systematically verify that.
* Please add a mention of the new capabilities to the \*added\* section of "CHANGELOG.md" as well as to the "supported SVG features" list in "SVG.md".

Don't worry that some of the test runs failed, that is an annoyance we need to address separately.

**Comment by gmischler** [comment]
Alright, one last thing that didn't previously catch my eye:
Your entry in CHANGELOG.md seems to be in the section for release 2.7.6, which is already out the door...

**Comment by gmischler** [comment]
Thanks for the excellent contribution, @afriedman412 !

Merging it now.

**Comment by Lucas-C** [comment]
Thank you for your excellent contribution @afriedman412,
and thanks for @gmischler for the review!

**Comment by Lucas-C** [comment]
@allcontributors please add @afriedman412 for code

**Pull request merged**
