### PR TITLE
Make a test independent of test infrastructure speed

### LINKED ISSUE #1067: Test failure in test_share_images_cache on fast computers
When running the tests I have a failure in test.image.test_load_image.test_share_images_cache:

```
>       assert duration.seconds > 0.25                               
E       assert 0.19840230899899325 > 0.25
```

I've noticed that that value has been recently changed, from 0.3 to 0.25 in commit 463a9e3a with the note “Test systems are faster than they used to”.

If I understand correctly the intent of the test, the important thing here is that the second execution takes less time than the first, so I've run the test locally with the following patch

```
 test/image/test_load_image.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/test/image/test_load_image.py b/test/image/test_load_image.py
index ef19221..508f65e 100644
--- a/test/image/test_load_image.py
+++ b/test/image/test_load_image.py
@@ -63,8 +63,8 @@ def test_share_images_cache(tmp_path):
 
     with time_execution() as duration:
         build_pdf_with_big_images()
-    assert duration.seconds > 0.25
+    first_time_duration = duration.seconds
 
     with time_execution() as duration:
         build_pdf_with_big_images()
-    assert duration.seconds < 0.3
+    assert duration.seconds < first_time_duration / 2
```

could it be a valid alternative (maybe with a different factor) that doesn't require updating every time the test systems get faster?

Please let me know if I have to turn this into a PR (I'm not really used to the github interface, but if I have to I can re-learn how to use it)

### PR DESCRIPTION
**Pull request by valholl**
Fixes #1067

**Checklist**:

- [ ] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [ ] A unit test is covering the code added / modified by this PR N/A

- [X] This PR is ready to be merged

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder N/A

- [ ] A mention of the change is present in `CHANGELOG.md` N/A?

I don't think this change is meaningful enough to warrant addition to the contributors table

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/py-pdf/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Comment by Lucas-C** [comment]
That's silly for such a small change,
but you need to run pretty-format the file you modified with:
`black test/image/test_load_image.py`

**Comment by Lucas-C** [comment]
@allcontributors please add @valholl for test

**Comment by valholl** [comment]
> That's silly for such a small change, but you need to pretty-format the file you modified with: `black test/image/test_load_image.py`

uops, thanks, I see that I've added a typo when copy/pasting, sorry :(

**Comment by valholl** [comment]
would you prefer a new PR with a single commit? (or is there a way to rebase the branch to squash the commits in this PR?)

**Comment by Lucas-C** [comment]
Thank you for your contribution @valholl!

**Pull request merged**
