### PR TITLE
Docs: Add Tutorial 5 to Tutorial.md

### PR DESCRIPTION
**Pull request by portfedh**
Hi !
I added Tutorial 5 to the tutorials page. 

For the tuto5.py code used I made a couple of changes:
    - I substituted the countries.txt file
        -  Before there were two lines: France;Paris;?;? and Spain;Madrid;?;?
        - I substituted it for a list of 30 countries
    - In the tutorial code I substituted the split symbol, from ";" to "," to make it look closer to a csv file.
    - I substituted the example file tuto5.pdf to reflect these changes.

Let me know If you´d like me to make any changes!

Pablo

### CODE REVIEW

**Comment by Lucas-C** [comment]
There is a minor conflict on `docs/Tutorial.md` in this PR.
You will have to rebase your branch: [GitHub doc](https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#rebase-and-merge-your-pull-request-commits) - [another in-depth tutorial using the `git` command](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request)

**Comment by portfedh** [comment]
I think I solved the conflict and made the requested changes. 

Thanks for the tutorial! It was very useful, I'm slowly getting the hang of it...

I made the changes on the git hub webpage, and plan to update my fork, local repository and continue from there with the next tutorial. Ill update again soon. : )

**Comment by portfedh** [comment]
Here goes Tutorial No. 6. 

I  also added a link at the start of the tutorial section to the FPDF documentation. I'm not sure if its appropriate, but if not I can remove it.

I couldn't find the link for the last method: write_html() so I left that out. 

I was about to write that I think i got the hang of how to rebase, but I see  there is some sort of conflict with the automatic checks. Not sure if it has something to do with that.

**Comment by portfedh** [comment]
Yes, please merge. Il send the 7th and last when I  get the chance, but I think its a bit longer, so it might be better to merge now.

**Comment by Lucas-C** [comment]
I did some minor refactoring in `Tutorial.md` to include code snippets from the `tutorial/` directory.

I also added mention of your contribution to the ChangeLog: https://github.com/PyFPDF/fpdf2/blob/master/CHANGELOG.md#added

**Comment by Lucas-C** [comment]
FYI I mentioned you in this blog article 😉
https://chezsoi.org/lucas/blog/hacktoberfest-on-fpdf2.html

**Pull request merged**
