### PR TITLE
Improve performance working with unicode fonts (#907)

### PR DESCRIPTION
**Pull request by andersonhc**
I am doing some tests using functools cache to improve performance working with unicode fonts.

test_cell/test_cell_speed_with_long_text is running 50% faster.

I will do additional tests soon.

**Checklist**:

- [ ] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [ ] A unit test is covering the code added / modified by this PR

- [ ] This PR is ready to be merged 

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [ ] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/py-pdf/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Review by gmischler — APPROVED** [review]
This is an very interesting approach.

We should probably test this with some longish text in chinese/japanese, or with a multilingual font. I suspect that a cache size of 128 is far too small in those cases (and I don't think increasing it will hurt anything with smaller alphabets).

**Comment by Lucas-C** [comment]
> test_cell/test_cell_speed_with_long_text is running 50% faster.

Wow, that is quite an improvement!
Good job @andersonhc!
This is very promising 🙂

**Comment by andersonhc** [comment]
Test command: pytest test/text/test_cell.py::test_cell_speed_with_long_text --durations=0

**pypi (latest release)**
```31.18s call     test/text/test_cell.py::test_cell_speed_with_long_text
29.97s call     test/text/test_cell.py::test_cell_speed_with_long_text
31.14s call     test/text/test_cell.py::test_cell_speed_with_long_text
32.86s call     test/text/test_cell.py::test_cell_speed_with_long_text
30.16s call     test/text/test_cell.py::test_cell_speed_with_long_text```

**Current master:**
```33.94s call     test/text/test_cell.py::test_cell_speed_with_long_text
30.42s call     test/text/test_cell.py::test_cell_speed_with_long_text
28.90s call     test/text/test_cell.py::test_cell_speed_with_long_text
33.58s call     test/text/test_cell.py::test_cell_speed_with_long_text
28.47s call     test/text/test_cell.py::test_cell_speed_with_long_text```

**PR branch:**
```11.38s call     test/text/test_cell.py::test_cell_speed_with_long_text
13.46s call     test/text/test_cell.py::test_cell_speed_with_long_text
12.00s call     test/text/test_cell.py::test_cell_speed_with_long_text
11.99s call     test/text/test_cell.py::test_cell_speed_with_long_text
13.00s call     test/text/test_cell.py::test_cell_speed_with_long_text```

**Comment by Lucas-C** [comment]
Thank you and good job for this @andersonhc! 👍

**Pull request merged**
