### PR TITLE
Correct Spelling in Khmer Tutorial Fpdf2 km

### PR DESCRIPTION
**Pull request by kuth-chi**
e.g. Fixes #0 

**Checklist**:

- [ ] The GitHub pipeline is OK (green), 
      meaning that both `pylint` (static code analyzer) and `black` (code formatter) are happy with the changes of this PR.

- [ ] A unit test is covering the code added / modified by this PR

- [ ] This PR is ready to be merged 

- [ ] In case of a new feature, docstrings have been added, with also some documentation in the `docs/` folder

- [ ] A mention of the change is present in `CHANGELOG.md`

By submitting this pull request, I confirm that my contribution is made under the terms of the [GNU LGPL 3.0 license](https://github.com/PyFPDF/fpdf2/blob/master/LICENSE).

### CODE REVIEW

**Comment by Lucas-C** [comment]
Hi!

Thank you for submitting some fixes.

Sadly, your PR has conflict with the `master` branch.
You should ensure that your fork is up-to-date with https://github.com/PyFPDF/fpdf2 before submitting a Pull Request.

Could rebase your branch please?

**Comment by kuth-chi** [comment]
> Hi!
> 
> Thank you for submitting some fixes.
> 
> Sadly, your PR has conflict with the `master` branch. You should ensure that your fork is up-to-date with https://github.com/PyFPDF/fpdf2 before submitting a Pull Request.
> 
> Could rebase your branch please?

So  I would like to change spelling from ភាសខ្មែរ​ to ភាសាខ្មែរ add some font face How to do it please
 <<<<<<< fpdf2-km
* [ភាសាខ្មែរ](Tutorial-km.md)
=======
* [ភាសខ្មែរ](Tutorial-km.md)
>>>>>>> master

**Comment by Lucas-C** [comment]
> So I would like to change spelling from ភាសខ្មែរ​ to ភាសាខ្មែរ add some font face How to do it please

Two options:

* if you know how to use `git`, or want to use this opportunity to learn, you rebase your branch based on the upstream repository `master` branch, and then `git push --force` to update this PR. GitHub has some great documentation on how to sync a fork with its upstream repository: https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-command-line

* you visit the page of this Markdown file on GitHub (here: https://github.com/PyFPDF/fpdf2/blob/master/docs/Tutorial-km.md ), then click on the "edit" button on the top right, perform your change a create a new Pull Request

**Comment by kuth-chi** [comment]
> > In face before I create pull request I have sync foked to my foke repository already but I don't know why it's still conflict when I push my branch and create pull request to master branch.
> 
> There are some commands you can perform to check that you have fully rebased the branch `fpdf2-km` on your fork:
> 
> ```
> # List the remote branches configured on your computer - upstream/master should be listed:
> git branch -r
> # Retrieve locally all the changes from the the upstream repo, that is PyFPDF/fpdf2:
> git fetch upstream
> # Switch locally to the branch of this Pull Request:
> git checkout fpdf2-km
> # Rebase your branch:
> git rebase upstream/master
> # Push your changes to GitHub - the --force option is required as you have rewritten your commit history:
> git push --force
> ```

Thank you

**Comment by Lucas-C** [comment]
Hi @kuth-chi

I resolved all the remaining merge conflicts.

Saldy, I do not see any change in this PR, it seems empty!

**Comment by Lucas-C** [comment]
Hi @kuth-chi

If you struggle with `git` & `GitHub`, you can simply point me to a version of the tutorial in which you have included your fixes, and I'll handle the commit/merge stuff 😉

**Comment by Lucas-C** [comment]
Hi @kuth-chi

Do you still wish to finish this contributuion?
Else I'm probably going to close this PR

**Comment by kuth-chi** [comment]
Yes

**Pull request closed without merging**
