### PR TITLE
New reference PDF files so that tests are compatible with fonttools==4.44.1

### PR DESCRIPTION
**Pull request by Lucas-C**
_cf._ issue https://github.com/py-pdf/fpdf2/issues/1021

Those 2 tests are currently still failing:
```
====================================================== short test summary info ======================================================
FAILED test/fonts/test_charmap.py::test_charmap_first_999_chars[cmss12.ttf] - AttributeError: 'table_O_S_2f_2' object has no attribute 'ulCodePageRange1'
FAILED test/table/test_table.py::test_table_with_ttf_font - AttributeError: 'table_O_S_2f_2' object has no attribute 'ulCodePageRange1'
================================================== 3 failed, 204 passed in 39.63s ===================================================
```

I hope to find a solution for hose in https://github.com/fonttools/fonttools/issues/3334
and will disable them for now in this PR

### CODE REVIEW

**Comment by Lucas-C** [comment]
There are still tests failing under Python 3.7.

We will need to include in this PR, for several unit tests, new calls to:
```python
@pytest.mark.skipif(
    sys.version_info < (3, 8),
    reason="fontTools dropped support for 3.7. https://github.com/py-pdf/fpdf2/pull/863",
)
```

**Comment by Lucas-C** [comment]
@andersonhc, @gmischler : would you agree that we remove Python 3.7 from our test matrix of Python versions tested in our GitHub Acdtions pipeline?

That seems to me like that the best solution there, and would avoid clutering our test suite with `pytest.mark.slipif(...)` annotations

**Comment by gmischler** [comment]
> @andersonhc, @gmischler : would you agree that we remove Python 3.7 from our test matrix of Python versions tested in our GitHub Acdtions pipeline?

Python 3.7 has formally reached [end of life](https://devguide.python.org/versions/) status a few months ago, While theoretically it would be nice to support older versions, if our core dependencies don't, then there's not much of a point in practise.

I haven't quite understood what fonttools 4.44.1 does differently though. Does it change the subset data that we embed in our files?

**Comment by andersonhc** [comment]
> @andersonhc, @gmischler : would you agree that we remove Python 3.7 from our test matrix of Python versions tested in our GitHub Acdtions pipeline?
 
I totally agree, python 3.7 has passed EOL and it's not worth going out of our way and finding workarounds to make sure those tests pass.

**Comment by Lucas-C** [comment]
Thank you for your feedbacks @andersonhc & @gmischler

Hence I merged this PR

> I haven't quite understood what fonttools 4.44.1 does differently though. Does it change the subset data that we embed in our files?

Yes, I think it does
_cf._ https://github.com/fonttools/fonttools/releases/tag/4.44.3
> [subset] Only prune codepage ranges for OS/2.version >= 1, ignore otherwise (https://github.com/fonttools/fonttools/issues/3334).

**Comment by Lucas-C** [comment]
Damn, they have yanked the latest fonttools release:
https://github.com/fonttools/fonttools/issues/3334#issuecomment-1812296388

I'm going to have to rollback this...

**Pull request merged**
