### PR TITLE
Better handling of fill_color in tables - fix #932

### LINKED ISSUE #932: set_fill_color fills the table column and html table
When I write `pdf.set_fill_color(*color)` for different task before the table, It fills columns with that color instead of the color given in the `pdf.table(**params)` with `params = { "cell_fill_color": (247, 248, 253), "cell_fill_mode":"COLUMNS", }`

**Example Code**
```python
from fpdf import FPDF
from fpdf.fonts import FontFace

pdf = FPDF()
pdf.add_page()

pdf.set_fill_color((126, 217, 87))
pdf.rect(x=10, y=15, w=185, h=8, style="F", round_corners=("TOP_RIGHT", "BOTTOM_RIGHT", "BOTTOM_LEFT", "TOP_LEFT"), corner_radius=8*2.5)

params = {
    "text_align": ("LEFT", "CENTER", "CENTER", "CENTER", "LEFT"),
    "width": 185,
    "col_widths": (50, 20, 20, 20, 75),
    "line_height":9,
    "cell_fill_color": (247, 248, 253),
    "cell_fill_mode":"COLUMNS",
    "borders_layout":"HORIZONTAL_LINES",
    "headings_style": FontFace(emphasis="B", color=(64,64,64), fill_color=(255,255,255), size_pt=12),
    }

summary_text = (
    ("A", "B", "C", "D", "E"),
    ("F", "", "", "", ""),
    ("G", "", "", "", ""), )

pdf.set_font(family="Times", style="B", size=12)
pdf.set_xy(15, 35)
with pdf.table(**params) as table:
    for data_row in summary_text:
        row = table.row()
        for data_cell in data_row:
            row.cell(data_cell)

pdf.output("output.pdf")
```

**Environment**
* **Operating System**: Ubuntu 22.04
* **Python version**: 3.11.4`
* **`fpdf2` version used**: 2.7.5

[output.pdf](https://github.com/py-pdf/fpdf2/files/12735309/output.pdf)
[output_expected.pdf](https://github.com/py-pdf/fpdf2/files/12735310/output_expected.pdf)

### PR DESCRIPTION
**Pull request by Lucas-C**
Table cell color will now be set following those settings, ordered by priority:

1. The cell `style`, provided to `Row.cell()`
2. The row `style`, provided to `Table.row()`
3. The table setting `headings_style.fill_color`, if the cell is part of some headings row
4. The table setting `cell_fill_color`, if `cell_fill_mode` indicates to fill a cell
5. The document `.fill_color` set before rendering the table

### CODE REVIEW

**Comment by Lucas-C** [comment]
@Iamrodos & @PODEDRA: as you have both expressed interest on this cell-coloring feature in the past, would be interested in reviewing this PR?

It is relatively short, and I'll be curious to know if you agree with the order of settings priorities I implemented.

This single unit test, introduced in this PR, should be enough to grasp the coloring logic:
* https://github.com/py-pdf/fpdf2/blob/issue-932/test/table/test_table.py#L678
* resulting PDF: https://github.com/py-pdf/fpdf2/blob/issue-932/test/table/table_with_fill_color_set_beforehand.pdf

**Comment by Lucas-C** [comment]
> Hi @Lucas-C ! I'm not a python wizz but this makes sense to me. I cannot think of any issues with these priorities, as long as they are all optional fields (which I believe they are?)

Thank you for the feedback!
Yes, they are all optionals 😊

**Comment by Iamrodos** [comment]
> @Iamrodos & @PODEDRA: as you have both expressed interest on this cell-coloring feature in the past, would be interested in reviewing this PR?
> 
> It is relatively short, and I'll be curious to know if you agree with the order of settings priorities I implemented.
> 
> This single unit test, introduced in this PR, should be enough to grasp the coloring logic:
> 
> * https://github.com/py-pdf/fpdf2/blob/issue-932/test/table/test_table.py#L678
> * resulting PDF: https://github.com/py-pdf/fpdf2/blob/issue-932/test/table/table_with_fill_color_set_beforehand.pdf

I may not understand FPDF enough to comment. The order looks like header then cell then document. I could be interpreting it wrong, but I would have thought the cell would have prioritised over the header. 

Color a cell in the order of
1. Cell fill color if set. This would take priority over header fill color if this cell is a header.
2. Header fill color, but only if this cell is a header.
3. PDF fill color if set.

Hope that may help and is not totally off base. 

Rod

**Comment by Lucas-C** [comment]
> Hope that may help and is not totally off base.

No, absolutely not, your comment was very relevant,
and made me realize that I should be even clearer in the code & documentation about some extra cases.

This is the new priority order that I will implement & describe in the docs:
1. The cell `style`, provided to `Row.cell()`
2. The row `style`, provided to `Table.row()`
3. The table setting `headings_style.fill_color`, if the cell is part of some headings row
4. The table setting `cell_fill_color`, if `cell_fill_mode` indicates to fill a cell
5. The document `.fill_color` set before rendering the table

**Comment by Iamrodos** [comment]
> This is the new priority order that I will implement & describe in the docs:
> 
> 1. The cell `style`, provided to `Row.cell()`
> 2. The row `style`, provided to `Table.row()`
> 3. The table setting `headings_style.fill_color`, if the cell is part of some headings row
> 4. The table setting `cell_fill_color`, if `cell_fill_mode` indicates to fill a cell
> 5. The document `.fill_color` set before rendering the table

Excellent list. Thats much clearer. Its easy to understand whats going on and what your options are.

**Pull request merged**
